spring.application.name=SRIE
#Conexion con MySQL
#spring.datasource.url=jdbc:mysql://localhost:3306/srie?useSSL=false&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=root1234
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Conexion a la base de datos remota
spring.datasource.url=jdbc:postgresql://ep-young-rain-at0vs6sc-pooler.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_1KTfUtRy8QDO
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect



